# config.py

WINDOW_WIDTH = 850
WINDOW_HEIGHT = 650

PIXEL_SIZE_DEFAULT = 10
PIXEL_SIZE_MIN = 5
PIXEL_SIZE_MAX = 30

DISPLAY_MAX_WIDTH = 800
DISPLAY_MAX_HEIGHT = 600

DEFAULT_PALETTE_FILE = "assets\palette_defalt.json"