# config.py
PIXEL_SIZE_MIN = 1
PIXEL_SIZE_MAX = 50
PIXEL_SIZE_DEFAULT = 10
DISPLAY_MAX_WIDTH = 800
DISPLAY_MAX_HEIGHT = 600
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700
DEFAULT_PALETTE_FILE = "palette\palette_defalt.json"
